name: .NET

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dotnet tool
      run: dotnet tool install -g dotnetCampus.TagToVersion
    - name: Set tag to version
      run: dotnet TagToVersion -t ${{ github.ref }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      
